# This Makefile creates files by downloading the values already generated by Anna and uploaded on SyncAndShare.
# To create the files yourself, use system/controller/reachability_estimator/Makefile

data:
	mkdir -p $@

data/data.zip: | data
	wget https://syncandshare.lrz.de/dl/fi2PvsoTCgHNwra5QXrEwP/data.zip -O data/data.zip.part --continue
	mv data/data.zip.part data/data.zip

system/bio_model/data/bc_model/transformations.npz:
	python system/bio_model/bc_network/bc_encoding.py

system/controller/reachability_estimator/data/models/re_mse_weights.50: data/data.zip
	unzip -p $< data/re/re_mse_weights.50 > $@

system/controller/reachability_estimator/data/reachability/dataset.hd5: data/data.zip
	unzip -p $< data/re/reachability_dataset.hd5 > $@

system/controller/bio_model/data/cognitive_map/after_exploration.gpickle: data/data.zip
	unzip -p $< data/bio_model/cognitive_map/after_exploration.gpickle > $@

#system/bio_model/data/cognitive_map/after_exploration.gpickle: system/controller/reachability_estimator/data/models/re_mse_weights.50
#	python system/controller/topological/exploration_phase.py

system/controller/reachability_estimator/data/trajectories/trajectories.hd5: data/data.zip
	unzip -p $< data/re/trajectories.hd5 > $@

walls = $(addsuffix .png,$(addprefix system/controller/simulation/environment/textures/walls/pattern-,$(shell seq 1 59)))

${walls}: system/controller/simulation/environment/textures/walls/pattern-%.png:
	python scripts/create_pattern.py 3x2 $@ $*

all-walls: ${walls}

system/controller/simulation/environment/linear_sunburst_map/maze_topview_binary.png: system/controller/simulation/environment/linear_sunburst_map/plane.urdf
	python scripts/create_occupancy_map.py linear_sunburst_map

.PHONY: all-walls
